// <auto-generated />
using System;
using JavisApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JavisApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260507172944_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.15");

            modelBuilder.Entity("JavisApi.Models.AppConfig", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("key");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_config");
                });

            modelBuilder.Entity("JavisApi.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("action");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("decision");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<Guid>("PrincipalId")
                        .HasColumnType("TEXT")
                        .HasColumnName("principal_id");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("principal_type");

                    b.Property<string>("Reason")
                        .HasColumnType("TEXT")
                        .HasColumnName("reason");

                    b.Property<string>("ResourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_id");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("resource_type");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT")
                        .HasColumnName("timestamp");

                    b.HasKey("Id");

                    b.HasIndex("PrincipalId");

                    b.HasIndex("Timestamp");

                    b.ToTable("audit_log");
                });

            modelBuilder.Entity("JavisApi.Models.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("departments");
                });

            modelBuilder.Entity("JavisApi.Models.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomRoleId")
                        .HasColumnType("TEXT")
                        .HasColumnName("custom_role_id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("department_id");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_active");

                    b.Property<DateTime?>("LastConnected")
                        .HasColumnType("TEXT")
                        .HasColumnName("last_connected");

                    b.Property<string>("McpToken")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("mcp_token");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomRoleId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("McpToken")
                        .IsUnique();

                    b.ToTable("employees");
                });

            modelBuilder.Entity("JavisApi.Models.KnowledgeType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("color");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<int>("SortOrder")
                        .HasColumnType("INTEGER")
                        .HasColumnName("sort_order");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("knowledge_types");
                });

            modelBuilder.Entity("JavisApi.Models.Note", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("NoteType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("note_type");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("notes");
                });

            modelBuilder.Entity("JavisApi.Models.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("WorkspaceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("workspace_type");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.ToTable("projects");
                });

            modelBuilder.Entity("JavisApi.Models.ProjectMember", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("employee_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("role");

                    b.HasKey("ProjectId", "EmployeeId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("project_members");
                });

            modelBuilder.Entity("JavisApi.Models.ProjectSource", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("TEXT")
                        .HasColumnName("project_id");

                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<DateTime>("AddedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("added_at");

                    b.HasKey("ProjectId", "SourceId");

                    b.HasIndex("SourceId");

                    b.ToTable("project_sources");
                });

            modelBuilder.Entity("JavisApi.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("INTEGER")
                        .HasColumnName("is_system");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<string>("PermissionsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("permissions");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles");
                });

            modelBuilder.Entity("JavisApi.Models.Skill", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("INTEGER")
                        .HasColumnName("current_version");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("name");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_type");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_path");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("VersionHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("version_hash");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("skills");
                });

            modelBuilder.Entity("JavisApi.Models.SkillDepartment", b =>
                {
                    b.Property<Guid>("SkillId")
                        .HasColumnType("TEXT")
                        .HasColumnName("skill_id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("department_id");

                    b.HasKey("SkillId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("skill_departments");
                });

            modelBuilder.Entity("JavisApi.Models.SkillVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("Changelog")
                        .HasColumnType("TEXT")
                        .HasColumnName("changelog");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_by");

                    b.Property<Guid>("SkillId")
                        .HasColumnType("TEXT")
                        .HasColumnName("skill_id");

                    b.Property<string>("StoragePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("storage_path");

                    b.Property<string>("VersionHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .HasColumnName("version_hash");

                    b.Property<int>("VersionNumber")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version_number");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("SkillId");

                    b.ToTable("skill_versions");
                });

            modelBuilder.Entity("JavisApi.Models.Source", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("ContributedByEmployeeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("contributed_by_employee_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT")
                        .HasColumnName("error_message");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_name");

                    b.Property<string>("FilePath")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT")
                        .HasColumnName("file_path");

                    b.Property<long?>("FileSize")
                        .HasColumnType("INTEGER")
                        .HasColumnName("file_size");

                    b.Property<string>("FullText")
                        .HasColumnType("TEXT")
                        .HasColumnName("full_text");

                    b.Property<string>("JobId")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("job_id");

                    b.Property<Guid?>("KnowledgeTypeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_type_id");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("metadata_json");

                    b.Property<string>("MinioKey")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("minio_key");

                    b.Property<string>("OutlineJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("outline_json");

                    b.Property<string>("PageOffsetsJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("page_offsets_json");

                    b.Property<int>("Progress")
                        .HasColumnType("INTEGER")
                        .HasColumnName("progress");

                    b.Property<string>("ProgressMessage")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("progress_message");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_type");

                    b.Property<string>("SourceType")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("source_type");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<string>("Url")
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex("ContributedByEmployeeId");

                    b.HasIndex("KnowledgeTypeId");

                    b.ToTable("sources");
                });

            modelBuilder.Entity("JavisApi.Models.SourceDepartment", b =>
                {
                    b.Property<Guid>("SourceId")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_id");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("TEXT")
                        .HasColumnName("department_id");

                    b.HasKey("SourceId", "DepartmentId");

                    b.HasIndex("DepartmentId");

                    b.ToTable("source_departments");
                });

            modelBuilder.Entity("JavisApi.Models.WikiLink", b =>
                {
                    b.Property<string>("FromSlug")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("from_slug");

                    b.Property<string>("ToSlug")
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("to_slug");

                    b.HasKey("FromSlug", "ToSlug");

                    b.ToTable("wiki_links");
                });

            modelBuilder.Entity("JavisApi.Models.WikiPage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ContentMd")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_md");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("KnowledgeTypeSlugsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("knowledge_type_slugs_json");

                    b.Property<bool>("Orphaned")
                        .HasColumnType("INTEGER")
                        .HasColumnName("orphaned");

                    b.Property<string>("PageType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("page_type");

                    b.Property<Guid?>("ScopeId")
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_id");

                    b.Property<string>("ScopeType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("scope_type");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT")
                        .HasColumnName("slug");

                    b.Property<string>("SourceIdsJson")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("source_ids_json");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Slug", "ScopeType", "ScopeId")
                        .IsUnique();

                    b.ToTable("wiki_pages");
                });

            modelBuilder.Entity("JavisApi.Models.WikiPageDraft", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<Guid?>("AuthorId")
                        .HasColumnType("TEXT")
                        .HasColumnName("author_id");

                    b.Property<string>("ContentMd")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_md");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("TEXT")
                        .HasColumnName("note");

                    b.Property<Guid>("PageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("page_id");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_at");

                    b.Property<Guid?>("ReviewedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewed_by_id");

                    b.Property<string>("ReviewerNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("reviewer_note");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT")
                        .HasColumnName("source");

                    b.Property<string>("SourceMetadataJson")
                        .HasColumnType("TEXT")
                        .HasColumnName("source_metadata_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("PageId");

                    b.HasIndex("ReviewedById");

                    b.HasIndex("Status");

                    b.ToTable("wiki_page_drafts");
                });

            modelBuilder.Entity("JavisApi.Models.WikiPageRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasColumnName("id");

                    b.Property<string>("ChangeNote")
                        .HasColumnType("TEXT")
                        .HasColumnName("change_note");

                    b.Property<string>("ChangeType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT")
                        .HasColumnName("change_type");

                    b.Property<Guid?>("ChangedById")
                        .HasColumnType("TEXT")
                        .HasColumnName("changed_by_id");

                    b.Property<string>("ContentMd")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("content_md");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DraftId")
                        .HasColumnType("TEXT")
                        .HasColumnName("draft_id");

                    b.Property<Guid>("PageId")
                        .HasColumnType("TEXT")
                        .HasColumnName("page_id");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("ChangedById");

                    b.HasIndex("PageId", "Version");

                    b.ToTable("wiki_page_revisions");
                });

            modelBuilder.Entity("JavisApi.Models.Employee", b =>
                {
                    b.HasOne("JavisApi.Models.Role", "CustomRole")
                        .WithMany("Employees")
                        .HasForeignKey("CustomRoleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JavisApi.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CustomRole");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("JavisApi.Models.Project", b =>
                {
                    b.HasOne("JavisApi.Models.Employee", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("JavisApi.Models.ProjectMember", b =>
                {
                    b.HasOne("JavisApi.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JavisApi.Models.Project", "Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("JavisApi.Models.ProjectSource", b =>
                {
                    b.HasOne("JavisApi.Models.Project", "Project")
                        .WithMany("ProjectSources")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JavisApi.Models.Source", "Source")
                        .WithMany()
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("JavisApi.Models.SkillDepartment", b =>
                {
                    b.HasOne("JavisApi.Models.Department", "Department")
                        .WithMany("SkillDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JavisApi.Models.Skill", "Skill")
                        .WithMany("SkillDepartments")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("JavisApi.Models.SkillVersion", b =>
                {
                    b.HasOne("JavisApi.Models.Employee", "Author")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("JavisApi.Models.Skill", "Skill")
                        .WithMany("Versions")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Skill");
                });

            modelBuilder.Entity("JavisApi.Models.Source", b =>
                {
                    b.HasOne("JavisApi.Models.Employee", "Contributor")
                        .WithMany()
                        .HasForeignKey("ContributedByEmployeeId");

                    b.HasOne("JavisApi.Models.KnowledgeType", "KnowledgeType")
                        .WithMany()
                        .HasForeignKey("KnowledgeTypeId");

                    b.Navigation("Contributor");

                    b.Navigation("KnowledgeType");
                });

            modelBuilder.Entity("JavisApi.Models.SourceDepartment", b =>
                {
                    b.HasOne("JavisApi.Models.Department", "Department")
                        .WithMany("SourceDepartments")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JavisApi.Models.Source", "Source")
                        .WithMany("SourceDepartments")
                        .HasForeignKey("SourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Source");
                });

            modelBuilder.Entity("JavisApi.Models.WikiPageDraft", b =>
                {
                    b.HasOne("JavisApi.Models.Employee", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JavisApi.Models.WikiPage", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("JavisApi.Models.Employee", "Reviewer")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Author");

                    b.Navigation("Page");

                    b.Navigation("Reviewer");
                });

            modelBuilder.Entity("JavisApi.Models.WikiPageRevision", b =>
                {
                    b.HasOne("JavisApi.Models.Employee", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedById")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("JavisApi.Models.WikiPage", "Page")
                        .WithMany()
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Page");
                });

            modelBuilder.Entity("JavisApi.Models.Department", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("SkillDepartments");

                    b.Navigation("SourceDepartments");
                });

            modelBuilder.Entity("JavisApi.Models.Project", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("ProjectSources");
                });

            modelBuilder.Entity("JavisApi.Models.Role", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("JavisApi.Models.Skill", b =>
                {
                    b.Navigation("SkillDepartments");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("JavisApi.Models.Source", b =>
                {
                    b.Navigation("SourceDepartments");
                });
#pragma warning restore 612, 618
        }
    }
}
